language: cpp
dist: bionic
compiler: gcc

before_install:
- sudo apt-get install ninja-build
before_script:
- cmake -GNinja .
script:
- env
- cmake --version
- ninja --version
- gcc --version
- g++ --version
- time ninja
- time ninja test 
