language: cpp
dist: bionic
compiler: gcc

before_install:
- sudo apt-get -q ninja-build
before_script:
- cmake -GNinja .
script:
- env
- cmake --version
- ninja --version
- gcc --version
- g++ --version
- ninja
- ninja test 
